[versions]
lwjgl = "3.3.4"
junit-jupiter = "5.10.2"
commons-math3 = "3.6.1"
guava = "33.0.0-jre"

[libraries]
# LWJGL Core
lwjgl-bom = { module = "org.lwjgl:lwjgl-bom", version.ref = "lwjgl" }
lwjgl-core = { module = "org.lwjgl:lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl" }
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb" }
lwjgl-openal = { module = "org.lwjgl:lwjgl-openal" }
lwjgl-assimp = { module = "org.lwjgl:lwjgl-assimp" }

# Test
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

# Utilities
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[bundles]
lwjgl-core = ["lwjgl-core", "lwjgl-glfw", "lwjgl-opengl"]