[versions]
lwjgl = "3.3.4"
junit-jupiter = "5.10.2"

[libraries]
# LWJGL Core
lwjgl-bom = { module = "org.lwjgl:lwjgl-bom", version.ref = "lwjgl" }
lwjgl-core = { module = "org.lwjgl:lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl" }
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb" }
lwjgl-openal = { module = "org.lwjgl:lwjgl-openal" }
lwjgl-assimp = { module = "org.lwjgl:lwjgl-assimp" }

# Test
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[bundles]
lwjgl-core = ["lwjgl-core", "lwjgl-glfw", "lwjgl-opengl"]